name: golangci-lint

on: ['push', 'pull_request']

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: go build -ldflags="-s -w" -v -o bot-linux-amd64 .

      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          file: bot-linux-amd64
          args: "--best --lzma"
          strip: true

      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bot-linux-amd64
          path: bot-linux-amd64

  image:
    name: image
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/uselections-2020